[package]
name = "survsim_planner"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
highs = "1.6.1"
highs-sys = { version = "1.6.1", features = ["libz"] }
hprof = "0.1.3"
log = "0.4.22"
ordered-float = "4.3.0"
serde_json = "1.0.128"
survsim_structs = { path = "../structs" }
tinyvec = { version = "1.8.0", features = ["alloc"] }
